### ISSUE TITLE
Failed to install using CocoaPod

### ISSUE THREAD

**Issue by Jensen-JZ** [engmahsa/HLSParser#2]
Thank you for creating such a useful tool, but there was a problem when I tried to install your HLSParser using CocoaPods. Your code files did not appear in my folder. Can you help me?

**Comment by Jensen-JZ** [comment]
Well, I've found a curve-saving solution, and it seems that Apple's native AVKit can meet my needs.

**Comment by engmahsa** [comment]
> Well, I've found a curve-saving solution, and it seems that Apple's native AVKit can meet my needs.

Hey Jen, Sorry, I didn't see your message. I am so glad that your problem has been solved.
